application_new_bureau:
    path:     /new
    defaults: { _controller: "ApplicationPlateformeBundle:Bureau:new" }

application_delete_bureau:
    path:     /delete/{id}
    defaults: { _controller: "ApplicationPlateformeBundle:Bureau:delete" }

application_edit_bureau:
    path:     /edit/{id}
    defaults: { _controller: "ApplicationPlateformeBundle:Bureau:edit" }

application_index_bureau:
    path:     /
    defaults: { _controller: "ApplicationPlateformeBundle:Bureau:index" }

application_actif_inactif_bureau:
    path:     /actifInactif/{id}
    defaults: { _controller: "ApplicationPlateformeBundle:Bureau:actifInactif" }

application_ajax_search_bureau:
    path:     /ajaxSearch
    defaults: { _controller: "ApplicationPlateformeBundle:Bureau:ajaxSearch" }
    options:
        expose: true

application_ajax_search_bureau_temporaire:
    path:     /searchBureauTemporaire
    defaults: { _controller: "ApplicationPlateformeBundle:Bureau:searchBureauTemporaire" }
    options:
        expose: true

application_show_bureau:
    path:     /showCalendar
    defaults: { _controller: "ApplicationPlateformeBundle:Bureau:showCalendar" }
    options:
        expose: true