application_csv_getListBeneficiaire:
    path:     /getListBeneficiaire
    defaults: { _controller: "ApplicationPlateformeBundle:Csv:getListBeneficiaire" }
    options:
        expose: true

application_csv_getListFacture:
    path:     /getListFacture
    defaults: { _controller: "ApplicationPlateformeBundle:Csv:getListFacture" }
    options:
        expose: true

application_csv_getFileEmployeur:
    path:     /getFileEmployeur
    defaults: { _controller: "ApplicationPlateformeBundle:Csv:getFileEmployeur" }
    options:
        expose: true

