application_new_document:
    path:     /new/{id}
    defaults: { _controller: "ApplicationPlateformeBundle:Document:new" }
    options:
        expose:  true


application_show_document:
    path: /show/{path}
    defaults: { _controller: "ApplicationPlateformeBundle:Document:show" }