application_new_document:
    path:     /new/{id}
    defaults: { _controller: "ApplicationPlateformeBundle:Document:new" }
    options:
        expose:  true

application_show_document:
    path: /show/{path}
    defaults: { _controller: "ApplicationPlateformeBundle:Document:show" }

application_update_document:
    path: /update/{id}
    defaults: { _controller: "ApplicationPlateformeBundle:Document:update" }

application_delete_document:
    path:     /delete/{id}
    defaults: { _controller: "ApplicationPlateformeBundle:Document:delete" }

application_up_document:
    path:    /up/{id}
    defaults: { _controller: "ApplicationPlateformeBundle:Document:up" }
    options:
        expose: true