application_add_news:
    path:     /add/{id}
    defaults: { _controller: "ApplicationPlateformeBundle:News:addStatut" }
    
application_new_news:
    path:     /new/{id}
    defaults: { _controller: "ApplicationPlateformeBundle:News:new" }
    options:
        expose:  true

application_show_all_news:
    path:     /showAll
    defaults: { _controller: "ApplicationPlateformeBundle:news:showAll" }

application_delete_news:
    path:     /delete/{id}
    defaults: { _controller: "ApplicationPlateformeBundle:News:delete" }

application_edit_news:
    path:     /update/{id}
    defaults: { _controller: "ApplicationPlateformeBundle:News:update" }