application_search_ville:
    path:     /search/{cp}
    defaults: { _controller: "ApplicationPlateformeBundle:Ville:ajaxSearchByCp" }
    options:
        expose:  true

application_get_ville:
    path:     /getVille
    defaults: { _controller: "ApplicationPlateformeBundle:Ville:ajaxGetVille" }
    options:
        expose: true

application_get_dpt_by_region_ville:
    path:     /getDptByRegion/{region}
    defaults: { _controller: "ApplicationPlateformeBundle:Ville:getDptByRegion" }
    options:
        expose: true